import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// Catálogo definido em docs/planning/catalogo-de-precos.md.
// Cobrança via Mercado Pago, "através de pessoa física" (ver docs/planning/integracao-mercado-pago.md):
// o payer é sempre o CPF do dono da conta (aluno, personal ou gestor da academia) — sem CNPJ/NFS-e
// obrigatórios agora. Add-ons (professor extra, +100 alunos, unidade extra) não são linhas nesta
// tabela ainda — ficam em `recursos` como referência de preço até termos um modelo de add-on.
const planos = [
  {
    codigo: 'ALUNO_MENSAL',
    nome: 'Aluno Premium',
    descricao: 'Acesso completo: biblioteca de planos, evolução avançada, clubes e relatórios',
    papel_alvo: 'ALUNO' as const,
    preco_mensal_cents: 1200,
    moeda: 'BRL',
    google_play_product_id: 'sub_aluno_mensal',
    trial_dias: 15,
    limite_alunos: null,
    faixa_min_alunos: 0,
    faixa_max_alunos: null,
    professores_inclusos: 0,
    unidades_inclusas: 0,
    preco_aluno_excedente_cents: null,
    recursos: { biblioteca_planos: true, evolucao_avancada: true, clubes: true, relatorios: true },
    ordem: 0,
    ativo: true,
  },
  {
    // Desativado (2026-09-17): todo novo cadastro passa por trial de 15 dias com cartão —
    // não existe mais opção de ficar de graça pra sempre. Quem já estava no PT_FREE continua
    // com a assinatura ativa (grandfather); `ativo: false` só impede novas seleções deste plano.
    codigo: 'PT_FREE',
    nome: 'Personal Free',
    descricao: 'Até 3 alunos ativos — treinos, execução e perfil',
    papel_alvo: 'PROFESSOR' as const,
    preco_mensal_cents: 0,
    moeda: 'BRL',
    google_play_product_id: null,
    trial_dias: 0,
    limite_alunos: 3,
    faixa_min_alunos: 0,
    faixa_max_alunos: 3,
    professores_inclusos: 1,
    unidades_inclusas: 1,
    preco_aluno_excedente_cents: null,
    recursos: {},
    ordem: 10,
    ativo: false,
  },
  {
    codigo: 'PT_STARTER',
    nome: 'Personal Starter',
    descricao: 'Até 10 alunos ativos — avaliação física e convites',
    papel_alvo: 'PROFESSOR' as const,
    preco_mensal_cents: 4900,
    moeda: 'BRL',
    google_play_product_id: null,
    trial_dias: 15,
    limite_alunos: 10,
    faixa_min_alunos: 4,
    faixa_max_alunos: 10,
    professores_inclusos: 1,
    unidades_inclusas: 1,
    preco_aluno_excedente_cents: null,
    recursos: { avaliacao_fisica: true },
    ordem: 11,
    ativo: true,
  },
  {
    codigo: 'PT_PRO',
    nome: 'Personal Pro',
    descricao: 'Até 30 alunos ativos — relatórios, laudos e correlações',
    papel_alvo: 'PROFESSOR' as const,
    preco_mensal_cents: 8900,
    moeda: 'BRL',
    google_play_product_id: null,
    trial_dias: 15,
    limite_alunos: 30,
    faixa_min_alunos: 11,
    faixa_max_alunos: 30,
    professores_inclusos: 1,
    unidades_inclusas: 1,
    preco_aluno_excedente_cents: null,
    recursos: { avaliacao_fisica: true, relatorios: true, correlacoes: true, clubes: true },
    ordem: 12,
    ativo: true,
  },
  {
    codigo: 'PT_PLUS',
    nome: 'Personal Plus',
    descricao: 'Até 60 alunos ativos — templates ilimitados e marca no app',
    papel_alvo: 'PROFESSOR' as const,
    preco_mensal_cents: 14900,
    moeda: 'BRL',
    google_play_product_id: null,
    trial_dias: 15,
    limite_alunos: 60,
    faixa_min_alunos: 31,
    faixa_max_alunos: 60,
    professores_inclusos: 2,
    unidades_inclusas: 1,
    preco_aluno_excedente_cents: null,
    recursos: { avaliacao_fisica: true, relatorios: true, correlacoes: true, clubes: true, templates_ilimitados: true, addon_professor_extra_cents: 3900 },
    ordem: 13,
    ativo: true,
  },
  {
    codigo: 'PT_SCALE',
    nome: 'Personal Scale',
    descricao: 'Até 120 alunos ativos — importação de alunos e suporte prioritário',
    papel_alvo: 'PROFESSOR' as const,
    preco_mensal_cents: 24900,
    moeda: 'BRL',
    google_play_product_id: null,
    trial_dias: 15,
    limite_alunos: 120,
    faixa_min_alunos: 61,
    faixa_max_alunos: 120,
    professores_inclusos: 3,
    unidades_inclusas: 1,
    preco_aluno_excedente_cents: null,
    recursos: { avaliacao_fisica: true, relatorios: true, correlacoes: true, clubes: true, templates_ilimitados: true, importacao_alunos: true, suporte_prioritario: true, addon_professor_extra_cents: 3900 },
    ordem: 14,
    ativo: true,
  },
  {
    codigo: 'PT_STUDIO',
    nome: 'Personal Studio',
    descricao: 'Alunos ilimitados (fair-use) — workspace com 3 professores e white-label básico',
    papel_alvo: 'PROFESSOR' as const,
    preco_mensal_cents: 34900,
    moeda: 'BRL',
    google_play_product_id: null,
    trial_dias: 15,
    limite_alunos: null,
    faixa_min_alunos: 121,
    faixa_max_alunos: null,
    professores_inclusos: 3,
    unidades_inclusas: 1,
    preco_aluno_excedente_cents: null,
    recursos: { avaliacao_fisica: true, relatorios: true, correlacoes: true, clubes: true, templates_ilimitados: true, importacao_alunos: true, suporte_prioritario: true, white_label_basico: true, addon_professor_extra_cents: 3900 },
    ordem: 15,
    ativo: true,
  },
  {
    codigo: 'AC_ESSENCIAL',
    nome: 'Academia Essencial',
    descricao: 'Academia pequena — até 150 alunos ativos, 5 professores, 1 unidade',
    papel_alvo: 'ACADEMIA' as const,
    preco_mensal_cents: 19900,
    moeda: 'BRL',
    google_play_product_id: null,
    trial_dias: 15,
    limite_alunos: 150,
    faixa_min_alunos: 0,
    faixa_max_alunos: 150,
    professores_inclusos: 5,
    unidades_inclusas: 1,
    preco_aluno_excedente_cents: null,
    recursos: { gestao_lote: true, clube_academia: true, addon_professor_extra_cents: 2900, addon_100_alunos_cents: 7900 },
    ordem: 20,
    ativo: true,
  },
  {
    codigo: 'AC_CRESCIMENTO',
    nome: 'Academia Crescimento',
    descricao: 'Academia média — até 400 alunos ativos, 15 professores, 1 unidade',
    papel_alvo: 'ACADEMIA' as const,
    preco_mensal_cents: 39900,
    moeda: 'BRL',
    google_play_product_id: null,
    trial_dias: 15,
    limite_alunos: 400,
    faixa_min_alunos: 151,
    faixa_max_alunos: 400,
    professores_inclusos: 15,
    unidades_inclusas: 1,
    preco_aluno_excedente_cents: null,
    recursos: { gestao_lote: true, clube_academia: true, relatorios: true, avaliacao_fisica: true, addon_professor_extra_cents: 2900, addon_100_alunos_cents: 7900, addon_unidade_extra_cents: 19900 },
    ordem: 21,
    ativo: true,
  },
  {
    codigo: 'AC_PERFORMANCE',
    nome: 'Academia Performance',
    descricao: 'Academia grande — até 1.000 alunos ativos, 40 professores, BI/multiunidade',
    papel_alvo: 'ACADEMIA' as const,
    preco_mensal_cents: 74900,
    moeda: 'BRL',
    google_play_product_id: null,
    trial_dias: 15,
    limite_alunos: 1000,
    faixa_min_alunos: 401,
    faixa_max_alunos: 1000,
    professores_inclusos: 40,
    unidades_inclusas: 1,
    preco_aluno_excedente_cents: null,
    recursos: { gestao_lote: true, clube_academia: true, relatorios: true, avaliacao_fisica: true, bi_multiunidade: true, marca_propria: true, addon_professor_extra_cents: 2900, addon_100_alunos_cents: 7900, addon_unidade_extra_cents: 19900 },
    ordem: 22,
    ativo: true,
  },
  {
    codigo: 'AC_REDE',
    nome: 'Academia Rede',
    descricao: 'Rede regional — até 2.500 alunos ativos, 100 professores, até 5 unidades',
    papel_alvo: 'ACADEMIA' as const,
    preco_mensal_cents: 149900,
    moeda: 'BRL',
    google_play_product_id: null,
    trial_dias: 15,
    limite_alunos: 2500,
    faixa_min_alunos: 1001,
    faixa_max_alunos: 2500,
    professores_inclusos: 100,
    unidades_inclusas: 5,
    preco_aluno_excedente_cents: null,
    recursos: { gestao_lote: true, clube_academia: true, relatorios: true, avaliacao_fisica: true, bi_multiunidade: true, marca_propria: true, addon_professor_extra_cents: 2900, addon_100_alunos_cents: 7900, addon_unidade_extra_cents: 19900 },
    ordem: 23,
    ativo: true,
  },
  {
    codigo: 'AC_ENTERPRISE',
    nome: 'Academia Enterprise',
    descricao: 'Rede nacional — alunos/professores/unidades ilimitados, sob consulta',
    papel_alvo: 'ACADEMIA' as const,
    preco_mensal_cents: 0,
    moeda: 'BRL',
    google_play_product_id: null,
    trial_dias: 0,
    limite_alunos: null,
    faixa_min_alunos: 2501,
    faixa_max_alunos: null,
    professores_inclusos: 0,
    unidades_inclusas: 0,
    preco_aluno_excedente_cents: null,
    recursos: { sob_consulta: true, white_label: true, sso: true, sla: true },
    ordem: 24,
    ativo: true,
  },
]

async function main() {
  console.log('🌱 Seed de planos de assinatura (catálogo docs/planning/catalogo-de-precos.md)...')

  for (const plano of planos) {
    await prisma.planoAssinatura.upsert({
      where: { codigo: plano.codigo },
      update: plano,
      create: plano,
    })
    console.log(`  ✅ ${plano.nome} (${plano.codigo})`)
  }

  console.log('✅ Planos de assinatura criados/atualizados')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
