/**
 * sync-exercises-v2.ts
 * Importa 1.324 exercícios do exercises-dataset-main com GIFs reais e PT.
 * Executar: npx tsx apps/api/prisma/sync-exercises-v2.ts
 */

import { PrismaClient } from '@prisma/client'
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const prisma = new PrismaClient()
const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

function findDatasetPath(): string {
  const candidates = [
    path.join(__dirname, 'data', 'exercises.json'),
    path.join(process.cwd(), 'exercises-dataset-main', 'data', 'exercises.json'),
    path.join(__dirname, '..', '..', '..', 'exercises-dataset-main', 'data', 'exercises.json'),
  ]
  for (const c of candidates) {
    if (fs.existsSync(c)) return c
  }
  throw new Error('exercises.json nao encontrado! Verifique apps/api/prisma/data/exercises.json')
}

const API_BASE_URL = process.env.API_BASE_URL || 'http://localhost:3333'

const exerciseNameTranslations: Record<string, string> = {
  '3/4 sit-up': 'Abdominal 3/4',
  '45 side bend': 'Inclinacao Lateral 45',
  'air bike': 'Bicicleta no Ar',
  'alternate heel touchers': 'Toque Alternado no Calcanhar',
  'ankle circles': 'Rotacao de Tornozelo',
  'archer pull up': 'Barra Fixa Arqueiro',
  'archer push up': 'Flexao Arqueiro',
  'arm slingers hanging bent knee legs': 'Pernas Suspensas Joelho Dobrado',
  'arm slingers hanging straight legs': 'Pernas Suspensas Estendidas',
  'arms apart circular toe touch (male)': 'Toque Circular com Pernas Afastadas',
  'arms overhead full sit-up (male)': 'Abdominal Completo com Bracos Elevados',
  'assisted chest dip (kneeling)': 'Paralelas para Peito Assistido (Ajoelhado)',
  'assisted hanging knee raise': 'Elevacao de Joelhos Suspenso Assistido',
  'assisted lying calves stretch': 'Alongamento de Panturrilhas Deitado Assistido',
  'assisted lying glutes stretch': 'Alongamento de Gluteos Deitado Assistido',
  'assisted lying gluteus and piriformis stretch': 'Alongamento Gluteo e Piriforme Deitado Assistido',
  'assisted lying leg raise with lateral throw down': 'Elevacao de Pernas Deitado com Lancamento Lateral Assistido',
  'assisted lying leg raise with throw down': 'Elevacao de Pernas Deitado com Lancamento Assistido',
  'assisted motion russian twist': 'Torcao Russa com Movimento Assistido',
  'assisted parallel close grip pull-up': 'Barra Fixa Pegada Fechada Paralela Assistida',
  'assisted prone hamstring': 'Posterior de Coxa em Pronacao Assistido',
  'assisted prone lying quads stretch': 'Alongamento Quadriceps Deitado Pronacao Assistido',
  'assisted prone rectus femoris stretch': 'Alongamento Reto Femoral Pronado Assistido',
  'assisted pull-up': 'Barra Fixa Assistida',
  'assisted seated pectoralis major stretch with stability ball': 'Alongamento Peitoral Maior Sentado com Bola Assistido',
  'assisted side lying adductor stretch': 'Alongamento Adutor Deitado Lateral Assistido',
  'assisted sit-up': 'Abdominal Assistido',
  'assisted standing chin-up': 'Barra Fixa Supinada em Pe Assistida',
  'assisted standing pull-up': 'Barra Fixa em Pe Assistida',
  'assisted standing triceps extension (with towel)': 'Extensao de Triceps em Pe Assistida (com Toalha)',
  'assisted triceps dip (kneeling)': 'Paralelas Triceps Assistido (Ajoelhado)',
  'assisted wide-grip chest dip (kneeling)': 'Paralelas Peito Pegada Aberta Assistido (Ajoelhado)',
  'astride jumps (male)': 'Saltos com Pernas Afastadas',
  'back and forth step': 'Passo Frente e Tras',
  'back extension on exercise ball': 'Extensao de Costas na Bola',
  'back lever': 'Alavanca de Costas',
  'back pec stretch': 'Alongamento Peito e Costas',
  'backward jump': 'Salto para Tras',
  'balance board': 'Prancha de Equilibrio',
  'barbell bench press': 'Supino Reto com Barra',
  'barbell curl': 'Rosca Direta com Barra',
  'barbell deadlift': 'Levantamento Terra com Barra',
  'barbell lunge': 'Avanco com Barra',
  'barbell row': 'Remada com Barra',
  'barbell shrug': 'Encolhimento de Ombros com Barra',
  'barbell squat': 'Agachamento com Barra',
  'bench dip': 'Paralelas no Banco',
  'bench press': 'Supino Reto',
  'bent over barbell row': 'Remada Curvada com Barra',
  'bicycle crunch': 'Abdominal Bicicleta',
  'box jump': 'Salto na Caixa',
  'bulgarian split squat': 'Agachamento Bulgaro',
  'burpee': 'Burpee',
  'cable crossover': 'Crossover na Polia',
  'cable curl': 'Rosca na Polia',
  'cable fly': 'Crucifixo na Polia',
  'cable lateral raise': 'Elevacao Lateral na Polia',
  'cable pulldown': 'Puxada Alta na Polia',
  'cable row': 'Remada na Polia',
  'calf raise': 'Elevacao de Panturrilha',
  'chin-up': 'Barra Fixa Supinada',
  'close-grip barbell bench press': 'Supino Fechado com Barra',
  'concentration curl': 'Rosca Concentrada',
  'crunch': 'Abdominal',
  'deadlift': 'Levantamento Terra',
  'decline bench press': 'Supino Declinado',
  'decline crunch': 'Abdominal Declinado',
  'decline push-up': 'Flexao Declinada',
  'dip': 'Paralelas',
  'dumbbell bench press': 'Supino Reto com Halteres',
  'dumbbell curl': 'Rosca Biceps com Halteres',
  'dumbbell deadlift': 'Levantamento Terra com Halteres',
  'dumbbell fly': 'Crucifixo com Halteres',
  'dumbbell front raise': 'Elevacao Frontal com Halteres',
  'dumbbell lateral raise': 'Elevacao Lateral com Halteres',
  'dumbbell lunge': 'Avanco com Halteres',
  'dumbbell row': 'Remada com Haltere',
  'dumbbell shoulder press': 'Desenvolvimento com Halteres',
  'dumbbell shrug': 'Encolhimento de Ombros com Halteres',
  'dumbbell squat': 'Agachamento com Halteres',
  'face pull': 'Face Pull',
  'french press': 'Triceps Frances',
  'front raise': 'Elevacao Frontal',
  'glute bridge': 'Elevacao de Quadril',
  'goblet squat': 'Agachamento Goblet',
  'hammer curl': 'Rosca Martelo',
  'hanging knee raise': 'Elevacao de Joelhos Suspenso',
  'hanging leg raise': 'Elevacao de Pernas Suspenso',
  'hip thrust': 'Elevacao de Quadril (Hip Thrust)',
  'incline barbell bench press': 'Supino Inclinado com Barra',
  'incline dumbbell bench press': 'Supino Inclinado com Halteres',
  'incline push-up': 'Flexao Inclinada',
  'jumping jack': 'Polichinelo',
  'jumping jacks': 'Polichinelos',
  'kettlebell swing': 'Swing com Kettlebell',
  'lat pulldown': 'Puxada Alta no Pulley',
  'lateral raise': 'Elevacao Lateral',
  'leg extension': 'Cadeira Extensora',
  'leg press': 'Leg Press',
  'leg raise': 'Elevacao de Pernas',
  'lunges': 'Avanco',
  'lying leg curl': 'Mesa Flexora',
  'military press': 'Desenvolvimento Militar',
  'mountain climber': 'Escalador',
  'overhead press': 'Desenvolvimento',
  'overhead tricep extension': 'Triceps Acima da Cabeca',
  'plank': 'Prancha Abdominal',
  'preacher curl': 'Rosca Scott',
  'pull-up': 'Barra Fixa',
  'pullover': 'Pullover',
  'push-up': 'Flexao de Braco',
  'rear delt fly': 'Crucifixo Invertido',
  'reverse curl': 'Rosca Inversa',
  'reverse lunge': 'Avanco Reverso',
  'romanian deadlift': 'Levantamento Terra Romeno',
  'rope pushdown': 'Triceps Corda no Pulley',
  'russian twist': 'Torcao Russa',
  'seated cable row': 'Remada Sentada na Polia',
  'seated calf raise': 'Elevacao de Panturrilha Sentado',
  'seated leg curl': 'Cadeira Flexora',
  'shoulder press': 'Desenvolvimento',
  'shrug': 'Encolhimento de Ombros',
  'side plank': 'Prancha Lateral',
  'squat': 'Agachamento',
  'standing calf raise': 'Elevacao de Panturrilha em Pe',
  'step-up': 'Subida no Banco',
  't-bar row': 'Remada Cavalinho',
  'tricep dip': 'Paralelas para Triceps',
  'tricep extension': 'Extensao de Triceps',
  'tricep pushdown': 'Triceps no Pulley',
  'upright row': 'Remada Alta',
  'wide-grip pull-up': 'Barra Fixa Aberta',
  'all fours squad stretch': 'Alongamento Quadrupede',
  'alternate lateral pulldown': 'Puxada Lateral Alternada',
  'band alternating biceps curl': 'Rosca Biceps Alternada com Elastico',
  'band bench press': 'Supino com Elastico',
  'band bent-over hip extension': 'Extensao de Quadril Curvado com Elastico',
  'band bicycle crunch': 'Abdominal Bicicleta com Elastico',
  'band close-grip pulldown': 'Puxada Fechada com Elastico',
  'band close-grip push-up': 'Flexao Fechada com Elastico',
  'band concentration curl': 'Rosca Concentrada com Elastico',
  'band front lateral raise': 'Elevacao Lateral Frontal com Elastico',
  'band front raise': 'Elevacao Frontal com Elastico',
  'band hip lift': 'Elevacao de Quadril com Elastico',
  'band horizontal pallof press': 'Pallof Press Horizontal com Elastico',
  'band jack knife sit-up': 'Abdominal Canivete com Elastico',
  'back extension': 'Extensao de Costas',
  'bent-over row': 'Remada Curvada',
  'box squat': 'Agachamento no Banco',
  'calf stretch': 'Alongamento de Panturrilha',
  'chest dip': 'Paralelas para Peito',
  'chest fly': 'Crucifixo para Peito',
  'cross body crunch': 'Abdominal Cruzado',
  'donkey calf raise': 'Elevacao de Panturrilha Burrinho',
  'dumbbell pullover': 'Pullover com Halteres',
  'dumbbell step-up': 'Subida no Banco com Halteres',
  'ez bar curl': 'Rosca Barra W',
  'ez bar skullcrusher': 'Triceps Testa Barra W',
  'floor press': 'Supino no Chão',
  'flutter kicks': 'Chutes Alternados',
  'front squat': 'Agachamento Frontal',
  'glute kickback': 'Coice de Gluteo',
  'good morning': 'Bom Dia',
  'hack squat': 'Agachamento Hack',
  'hip abduction': 'Abducao de Quadril',
  'hip adduction': 'Aducao de Quadril',
  'kettlebell clean': 'Clean com Kettlebell',
  'kettlebell snatch': 'Snatch com Kettlebell',
  'kneeling push-up': 'Flexao Ajoelhado',
  'leg curl': 'Flexao de Pernas',
  'lying triceps extension': 'Triceps Testa Deitado',
  'medicine ball slam': 'Bola de Medicina no Chao',
  'oblique crunch': 'Abdominal Obliquo',
  'pistol squat': 'Agachamento Pistola',
  'reverse fly': 'Crucifixo Invertido',
  'reverse grip pulldown': 'Puxada Supinada',
  'seated row': 'Remada Sentado',
  'skull crusher': 'Triceps Testa',
  'smith machine squat': 'Agachamento na Smith',
  'smith machine bench press': 'Supino na Smith',
  'split squat': 'Agachamento Dividido',
  'stiff leg deadlift': 'Levantamento Terra Stiff',
  'sumo deadlift': 'Levantamento Terra Sumo',
  'tricep kickback': 'Triceps Coice',
  'tricep overhead extension': 'Triceps Acima da Cabeca',
  'wall sit': 'Agachamento na Parede',
  'wide-grip lat pulldown': 'Puxada Aberta no Pulley',
  'wrist curl': 'Rosca de Punho',
  'zottman curl': 'Rosca Zottman',
}

const muscleGroupPT: Record<string, string> = {
  'abs': 'Abdomen', 'abdominals': 'Abdomen', 'waist': 'Abdomen / Lombar',
  'back': 'Costas', 'lats': 'Dorsais', 'latissimus dorsi': 'Grande Dorsal',
  'upper back': 'Costas Superiores', 'lower back': 'Lombar',
  'rhomboids': 'Romboides', 'trapezius': 'Trapezio', 'traps': 'Trapezio',
  'chest': 'Peito', 'shoulders': 'Ombros', 'deltoids': 'Deltoides',
  'rotator cuff': 'Manguito Rotador', 'biceps': 'Biceps', 'triceps': 'Triceps',
  'forearms': 'Antebraccos', 'wrist extensors': 'Extensores do Punho',
  'wrist flexors': 'Flexores do Punho', 'wrists': 'Punhos', 'hands': 'Maos',
  'quads': 'Quadriceps', 'quadriceps': 'Quadriceps',
  'hamstrings': 'Posterior de Coxa', 'glutes': 'Gluteos',
  'calves': 'Panturrilhas', 'soleus': 'Soleo (Panturrilha)',
  'upper legs': 'Coxas', 'lower legs': 'Panturrilhas / Tibiais',
  'hip flexors': 'Flexores do Quadril', 'core': 'Core (Abdomen e Lombar)',
  'obliques': 'Obliquos', 'neck': 'Pescoco', 'ankles': 'Tornozelos',
  'ankle stabilizers': 'Estabilizadores do Tornozelo', 'cardio': 'Cardio',
  'upper arms': 'Bracos', 'lower arms': 'Antebraccos',
  'pectorals': 'Peitoral', 'delts': 'Deltoides', 'adductors': 'Adutores',
  'abductors': 'Abdutores', 'levator scapulae': 'Levantador da Escapula',
  'serratus anterior': 'Serrátil Anterior', 'spine': 'Coluna Vertebral',
  'cardiovascular system': 'Sistema Cardiovascular',
}

const equipmentPT: Record<string, string> = {
  'body weight': 'Peso Corporal', 'barbell': 'Barra', 'dumbbell': 'Halteres',
  'cable': 'Polia', 'machine': 'Maquina', 'leverage machine': 'Maquina de Alavanca',
  'smith machine': 'Maquina Smith', 'kettlebell': 'Kettlebell',
  'resistance band': 'Elastico de Resistencia', 'band': 'Elastico',
  'ez barbell': 'Barra W (EZ)', 'olympic barbell': 'Barra Olimpica',
  'trap bar': 'Barra Hexagonal', 'medicine ball': 'Bola de Medicina',
  'stability ball': 'Bola de Pilates', 'bosu ball': 'Bosu',
  'roller': 'Rolo de Liberacao Miofascial', 'rope': 'Corda',
  'weighted': 'Com Peso Adicional', 'assisted': 'Assistido',
  'stationary bike': 'Bicicleta Estacionaria', 'elliptical machine': 'Eliptico',
  'skierg machine': 'Remo Vertical (SkiErg)', 'sled machine': 'Treno de Arrasto',
  'stepmill machine': 'Escada Rolante', 'tire': 'Pneu',
  'hammer': 'Marreta', 'upper body ergometer': 'Ergometro de Bracos',
  'wheel roller': 'Roda Abdominal',
}

const bodyPartPT: Record<string, string> = {
  'waist': 'Abdomen / Lombar', 'back': 'Costas', 'chest': 'Peito',
  'shoulders': 'Ombros', 'upper arms': 'Bracos', 'lower arms': 'Antebraccos',
  'upper legs': 'Coxas', 'lower legs': 'Pernas Inferiores',
  'neck': 'Pescoco', 'cardio': 'Cardio',
}

function translateStep(step: string): string {
  const map: [RegExp, string][] = [
    [/lie flat on your back on the floor/gi, 'Deite-se de costas no chao com as costas totalmente apoiadas'],
    [/lie flat on your back/gi, 'Deite-se de costas no chao'],
    [/lie flat on a bench/gi, 'Deite-se em um banco reto'],
    [/lie on your back on the floor/gi, 'Deite-se de costas no chao'],
    [/lie on a flat bench/gi, 'Deite-se em um banco reto'],
    [/lie on your back on a flat bench/gi, 'Deite-se de costas em um banco reto'],
    [/lie on your back/gi, 'Deite-se de costas'],
    [/lie on your stomach/gi, 'Deite-se de brucos'],
    [/face down/gi, 'de brucos'],
    [/lie down on the floor/gi, 'Deite-se no chao'],
    [/lie face down on the floor/gi, 'Deite-se de brucos no chao'],
    [/lie down on your stomach/gi, 'Deite-se de brucos'],
    [/stand up straight/gi, 'Fique em pe com postura ereta'],
    [/stand upright/gi, 'Fique em pe com postura ereta'],
    [/stand with your feet shoulder.?width apart/gi, 'Fique em pe com os pes afastados na largura dos ombros'],
    [/stand with feet shoulder-width apart/gi, 'Fique em pe com os pes na largura dos ombros'],
    [/stand with your feet together/gi, 'Fique em pe com os pes juntos'],
    [/stand with your feet hip.?width apart/gi, 'Fique em pe com os pes na largura do quadril'],
    [/sit on the floor/gi, 'Sente-se no chao'],
    [/sit on a bench/gi, 'Sente-se em um banco'],
    [/sit on a flat bench/gi, 'Sente-se em um banco reto'],
    [/sit upright/gi, 'Sente-se com a coluna ereta'],
    [/sit on the machine/gi, 'Sente-se na maquina'],
    [/kneel on the floor/gi, 'Ajoelhe-se no chao'],
    [/get into a kneeling position/gi, 'Posicione-se ajoelhado'],
    [/get on all fours/gi, 'Fique na posicao quadrupede (quatro apoios)'],
    [/start in a plank position/gi, 'Comece na posicao de prancha'],
    [/start in a push.?up position/gi, 'Comece na posicao de flexao de braco'],
    [/get into a push.?up position/gi, 'Posicione-se como se fosse fazer uma flexao'],
    [/grab the bar(?:bell)?/gi, 'Segure a barra'],
    [/hold a dumbbell in each hand/gi, 'Segure um haltere em cada mao'],
    [/hold a dumbbell/gi, 'Segure um haltere'],
    [/hold a kettlebell/gi, 'Segure um kettlebell'],
    [/hold the handle with both hands/gi, 'Segure a alca com as duas maos'],
    [/grasp the bar/gi, 'Agarre a barra'],
    [/grasp the handles?/gi, 'Agarre as alcas'],
    [/grasp the band handles?/gi, 'Agarre as alcas do elastico'],
    [/grip the bar/gi, 'Segure firme a barra'],
    [/with an overhand grip/gi, 'com pegada pronada (palmas para frente)'],
    [/with an underhand grip/gi, 'com pegada supinada (palmas para voce)'],
    [/with a neutral grip/gi, 'com pegada neutra (palmas viradas uma para a outra)'],
    [/slightly wider than shoulder.?width/gi, 'ligeiramente mais aberto que a largura dos ombros'],
    [/slightly narrower than shoulder.?width/gi, 'ligeiramente mais fechado que a largura dos ombros'],
    [/shoulder.?width apart/gi, 'na largura dos ombros'],
    [/keep your back straight/gi, 'Mantenha as costas retas'],
    [/keep your back flat/gi, 'Mantenha as costas planas'],
    [/keep your spine neutral/gi, 'Mantenha a coluna em posicao neutra'],
    [/keep your core tight/gi, 'Mantenha o abdomen contraido'],
    [/keep your core engaged/gi, 'Mantenha o core ativado'],
    [/keep your abs tight/gi, 'Mantenha o abdomen contraido'],
    [/keep your chest up/gi, 'Mantenha o peito erguido'],
    [/keep your head neutral/gi, 'Mantenha a cabeca em posicao neutra'],
    [/keep your elbows close to your body/gi, 'Mantenha os cotovelos proximos ao corpo'],
    [/keep your elbows tucked/gi, 'Mantenha os cotovelos junto ao corpo'],
    [/keep your elbows slightly bent/gi, 'Mantenha os cotovelos levemente flexionados'],
    [/keep your arms straight/gi, 'Mantenha os bracos estendidos'],
    [/keep your legs straight/gi, 'Mantenha as pernas estendidas'],
    [/keep your knees slightly bent/gi, 'Mantenha os joelhos levemente flexionados'],
    [/keep your body in a straight line/gi, 'Mantenha o corpo alinhado em linha reta'],
    [/engage your (abs|core)/gi, 'Contraia o abdomen'],
    [/engaging your (abs|core)/gi, 'contraindo o abdomen'],
    [/brace your core/gi, 'Contraia o core'],
    [/squeeze your glutes/gi, 'Contraia os gluteos'],
    [/squeeze your shoulder blades/gi, 'Aproxime as escapulas'],
    [/squeezing your shoulder blades together/gi, 'aproximando as escapulas'],
    [/retract your shoulder blades/gi, 'Retraia as escapulas'],
    [/press your back against/gi, 'Pressione as costas contra'],
    [/press your feet flat/gi, 'Mantenha os pes apoiados no chao'],
    [/feet flat on the ground/gi, 'os pes totalmente apoiados no chao'],
    [/feet flat on the floor/gi, 'os pes apoiados no chao'],
    [/plant your feet firmly/gi, 'Apoie firmemente os pes no chao'],
    [/slowly lower/gi, 'Abaixe lentamente'],
    [/slowly lift/gi, 'Levante lentamente'],
    [/slowly raise/gi, 'Eleve lentamente'],
    [/slowly bend/gi, 'Flexione lentamente'],
    [/slowly extend/gi, 'Estenda lentamente'],
    [/slowly bring/gi, 'Traga lentamente'],
    [/slowly lower yourself/gi, 'Abaixe-se lentamente'],
    [/slowly return/gi, 'Retorne lentamente'],
    [/return to the starting position/gi, 'Retorne a posicao inicial'],
    [/return to start/gi, 'Volte a posicao inicial'],
    [/come back to starting position/gi, 'Volte a posicao inicial'],
    [/lower back down/gi, 'Abaixe de volta'],
    [/lower the weight/gi, 'Abaixe o peso'],
    [/lower yourself/gi, 'Abaixe-se'],
    [/lift the weight/gi, 'Levante o peso'],
    [/lift your arms/gi, 'Levante os bracos'],
    [/lift your legs/gi, 'Levante as pernas'],
    [/raise your arms/gi, 'Eleve os bracos'],
    [/raise your legs/gi, 'Eleve as pernas'],
    [/bend your knees/gi, 'Flexione os joelhos'],
    [/bend your elbows/gi, 'Flexione os cotovelos'],
    [/bend at the elbows/gi, 'Flexione os cotovelos'],
    [/bend at the waist/gi, 'Flexione na cintura'],
    [/extend your arms fully/gi, 'Estenda completamente os bracos'],
    [/extend your legs/gi, 'Estenda as pernas'],
    [/extend your hips/gi, 'Estenda o quadril'],
    [/fully extend your arms/gi, 'Estenda completamente os bracos'],
    [/straighten your arms/gi, 'Estique os bracos'],
    [/straighten your legs/gi, 'Estique as pernas'],
    [/straighten your body/gi, 'Alinhe o corpo'],
    [/pause at the top/gi, 'Faca uma pausa no topo do movimento'],
    [/pause for a moment/gi, 'Faca uma pausa por um momento'],
    [/pause briefly/gi, 'Faca uma breve pausa'],
    [/hold this position for/gi, 'Mantenha esta posicao por'],
    [/hold for a moment/gi, 'Segure por um momento'],
    [/hold at the top/gi, 'Segure no topo'],
    [/hold the contraction/gi, 'Segure a contracao'],
    [/hold for (\d+)-(\d+) seconds/gi, 'Segure por $1 a $2 segundos'],
    [/hold for (\d+) second/gi, 'Segure por $1 segundo'],
    [/repeat for the desired number of repetitions/gi, 'Repita pelo numero desejado de repeticoes'],
    [/repeat for recommended number/gi, 'Repita pelo numero recomendado de repeticoes'],
    [/repeat the movement/gi, 'Repita o movimento'],
    [/repeat on the other side/gi, 'Repita no outro lado'],
    [/repeat on the opposite side/gi, 'Repita no lado oposto'],
    [/continue alternating/gi, 'Continue alternando os lados'],
    [/switch sides/gi, 'Troque de lado'],
    [/switch legs/gi, 'Troque de perna'],
    [/switch arms/gi, 'Troque de braco'],
    [/alternate between left and right/gi, 'Alterne entre esquerdo e direito'],
    [/perform the movement in a controlled manner/gi, 'Execute o movimento de forma controlada'],
    [/in a controlled motion/gi, 'de forma controlada'],
    [/with control/gi, 'com controle'],
    [/do not lock your elbows/gi, 'Nao trave os cotovelos'],
    [/do not lock your knees/gi, 'Nao trave os joelhos'],
    [/do not arch your back/gi, 'Nao arquee as costas'],
    [/avoid arching your back/gi, 'Evite arquear as costas'],
    [/avoid locking your joints/gi, 'Evite travar as articulacoes'],
    [/avoid swinging/gi, 'Evite balancar o corpo'],
    [/do not use momentum/gi, 'Nao use impulso'],
    [/maintain a steady pace/gi, 'Mantenha um ritmo constante'],
    [/maintain proper form/gi, 'Mantenha a postura correta'],
    [/breathe in/gi, 'Inspire'],
    [/inhale/gi, 'Inspire'],
    [/breathe out/gi, 'Expire'],
    [/exhale/gi, 'Expire'],
    [/exhale as you/gi, 'Expire enquanto'],
    [/inhale as you/gi, 'Inspire enquanto'],
    [/take a deep breath/gi, 'Respire fundo'],
    [/push through your heels/gi, 'Empurre pelos calcanhares'],
    [/drive through your heels/gi, 'Forca nos calcanhares'],
    [/pull towards your chest/gi, 'Puxe em direcao ao peito'],
    [/pull the weight towards/gi, 'Puxe o peso em direcao a'],
    [/pull the bar towards/gi, 'Puxe a barra em direcao a'],
    [/pull the cable/gi, 'Puxe o cabo'],
    [/pull the band/gi, 'Puxe o elastico'],
    [/push through your chest/gi, 'Empurre usando o peito'],
    [/push the weight/gi, 'Empurre o peso'],
    [/push against/gi, 'Empurre contra'],
    [/press the weight/gi, 'Empurre o peso para cima'],
    [/press the bar/gi, 'Pressione a barra para cima'],
    [/your upper arms/gi, 'a parte superior dos bracos'],
    [/your upper body/gi, 'a parte superior do corpo'],
    [/your lower body/gi, 'a parte inferior do corpo'],
    [/upper body/gi, 'parte superior do corpo'],
    [/lower body/gi, 'parte inferior do corpo'],
    [/your feet/gi, 'seus pes'], [/your hands/gi, 'suas maos'],
    [/your arms/gi, 'seus bracos'], [/your legs/gi, 'suas pernas'],
    [/your knees/gi, 'seus joelhos'], [/your hips/gi, 'seu quadril'],
    [/your shoulders/gi, 'seus ombros'], [/your chest/gi, 'seu peito'],
    [/your back/gi, 'suas costas'], [/your core/gi, 'seu core'],
    [/your abs/gi, 'seu abdomen'], [/your head/gi, 'sua cabeca'],
    [/your neck/gi, 'seu pescoco'], [/your elbows/gi, 'seus cotovelos'],
    [/your wrists/gi, 'seus punhos'], [/your ankles/gi, 'seus tornozelos'],
    [/your glutes/gi, 'seus gluteos'],
    [/your thighs/gi, 'suas coxas'],
    [/the ground/gi, 'o chao'], [/the floor/gi, 'o chao'],
    [/the bench/gi, 'o banco'],
    [/the weight/gi, 'o peso'], [/the handle/gi, 'a alca'],
    [/the machine/gi, 'a maquina'],
    [/the cable/gi, 'o cabo'],
    [/the dumbbell/gi, 'o haltere'],
    [/the resistance band/gi, 'o elastico de resistencia'],
    [/the stability ball/gi, 'a bola de pilates'],
    [/the exercise ball/gi, 'a bola de exercicio'],
    [/with both hands/gi, 'com as duas maos'],
    [/with both legs/gi, 'com as duas pernas'],
    [/with your right hand/gi, 'com a mao direita'],
    [/with your left hand/gi, 'com a mao esquerda'],
    [/with your right leg/gi, 'com a perna direita'],
    [/with your left leg/gi, 'com a perna esquerda'],
    [/in front of you/gi, 'a sua frente'],
    [/to the side/gi, 'para o lado'],
    [/out to the sides/gi, 'para os lados'],
    [/at a 90.degree angle/gi, 'em um angulo de 90 graus'],
    [/(\d+)-(\d+) seconds/gi, '$1 a $2 segundos'],
    [/(\d+) seconds/gi, '$1 segundos'],
    [/(\d+) repetitions/gi, '$1 repeticoes'],
    [/(\d+) reps/gi, '$1 repeticoes'],
    [/(\d+) sets/gi, '$1 series'],
    [/throughout the movement/gi, 'durante todo o movimento'],
    [/through the full range of motion/gi, 'em toda a amplitude do movimento'],
    [/full range of motion/gi, 'amplitude completa do movimento'],
    [/a full range of motion/gi, 'a amplitude completa do movimento'],
    [/make sure/gi, 'Certifique-se de'],
    [/ensure that/gi, 'Garanta que'],
    [/focus on/gi, 'Concentre-se em'],
    [/concentrate on/gi, 'Concentre-se em'],
    [/this is your starting position/gi, 'Esta e a sua posicao inicial'],
    [/this will be your starting position/gi, 'Esta sera sua posicao inicial'],
    [/begin the movement/gi, 'Inicie o movimento'],
    [/begin the exercise/gi, 'Inicie o exercicio'],
    [/to perform the exercise/gi, 'para executar o exercicio'],
    [/to perform this exercise/gi, 'para executar este exercicio'],
    [/this exercise targets/gi, 'Este exercicio trabalha'],
    [/place your hands/gi, 'Posicione as maos'],
    [/place your feet/gi, 'Posicione os pes'],
    [/place the band/gi, 'Posicione o elastico'],
    [/attach the band/gi, 'Prenda o elastico'],
    [/anchor the band/gi, 'Fixe o elastico'],
    [/wrap the band/gi, 'Enrole o elastico'],
    [/step on the band/gi, 'Pise sobre o elastico'],
    [/step onto the band/gi, 'Pise sobre o elastico'],
    [/loop the band/gi, 'Passe o elastico em volta'],
    [/let the band/gi, 'Deixe o elastico'],
    [/position yourself/gi, 'Posicione-se'],
    [/set up/gi, 'Prepare'],
    [/adjust the machine/gi, 'Ajuste a maquina'],
    [/adjust the seat/gi, 'Ajuste o assento'],
    [/select the appropriate weight/gi, 'Selecione o peso adequado'],
    [/choose a weight/gi, 'Escolha um peso'],
    [/start with light weight/gi, 'Comece com peso leve'],
    [/warm up/gi, 'Aqueca'],
    [/cool down/gi, 'Esfrie'],
    [/if needed/gi, 'se necessario'],
    [/if necessary/gi, 'se necessario'],
    [/if possible/gi, 'se possivel'],
    [/as needed/gi, 'conforme necessario'],
    [/you can also/gi, 'Voce tambem pode'],
    [/you may also/gi, 'Voce tambem pode'],
    [/for added difficulty/gi, 'Para maior dificuldade'],
    [/for an extra challenge/gi, 'Para um desafio extra'],
    [/to increase the difficulty/gi, 'Para aumentar a dificuldade'],
    [/to make it easier/gi, 'Para facilitar'],
    [/to make it harder/gi, 'Para dificultar'],
    [/for better results/gi, 'Para melhores resultados'],
    [/for best results/gi, 'Para melhores resultados'],
    [/until you feel a stretch/gi, 'ate sentir um alongamento'],
    [/until you feel a slight stretch/gi, 'ate sentir um leve alongamento'],
    [/you should feel/gi, 'Voce deve sentir'],
    [/feel the stretch/gi, 'sinta o alongamento'],
    [/feel the contraction/gi, 'sinta a contracao'],
    [/without moving/gi, 'sem se mover'],
    [/without bending/gi, 'sem flexionar'],
    [/without rounding/gi, 'sem curvar'],
    [/without arching/gi, 'sem arquear'],
    [/keep the movement slow/gi, 'Mantenha o movimento lento'],
    [/control the movement/gi, 'Controle o movimento'],
    [/controlled movement/gi, 'movimento controlado'],
    [/smooth and controlled/gi, 'suave e controlado'],
    [/smooth motion/gi, 'movimento suave'],

    // ─── Conectores e palavras comuns que faltam ───
    [/\bwith\b/gi, 'com'],
    [/\band\b/gi, 'e'],
    [/\bor\b/gi, 'ou'],
    [/\bbut\b/gi, 'mas'],
    [/\bthen\b/gi, 'entao'],
    [/\balso\b/gi, 'tambem'],
    [/\bthis\b/gi, 'esta'],
    [/\bthat\b/gi, 'que'],

    // ─── Gerúndios ───
    [/\bholding\b/gi, 'segurando'],
    [/\bkeeping\b/gi, 'mantendo'],
    [/\bpushing\b/gi, 'empurrando'],
    [/\bpulling\b/gi, 'puxando'],
    [/\bpressing\b/gi, 'pressionando'],
    [/\blowering\b/gi, 'abaixando'],
    [/\blifting\b/gi, 'levantando'],
    [/\braising\b/gi, 'elevando'],
    [/\bextending\b/gi, 'estendendo'],
    [/\bbending\b/gi, 'flexionando'],
    [/\bsqueezing\b/gi, 'apertando'],
    [/\bengaging\b/gi, 'contraindo'],
    [/\bbringing\b/gi, 'trazendo'],
    [/\bplacing\b/gi, 'posicionando'],
    [/\bgrabbing\b/gi, 'agarrando'],
    [/\bstanding\b/gi, 'em pe'],
    [/\busing\b/gi, 'usando'],

    // ─── Preposições e advérbios ───
    [/\bagainst\b/gi, 'contra'],
    [/\bacross\b/gi, 'sobre'],
    [/\btowards?\b/gi, 'em direcao a'],
    [/\baway from\b/gi, 'para longe de'],
    [/\bbetween\b/gi, 'entre'],
    [/\bin front of\b/gi, 'a frente de'],
    [/\bnext to\b/gi, 'ao lado de'],
    [/\bclose to\b/gi, 'proximo de'],
    [/\bin line with\b/gi, 'alinhado com'],
    [/\bin the direction of\b/gi, 'na direcao de'],
    [/\bdown to\b/gi, 'ate'],
    [/\bback down\b/gi, 'de volta para baixo'],
    [/\bback up\b/gi, 'de volta para cima'],
    [/\bup to\b/gi, 'ate'],
    [/\bapart\b/gi, 'afastados'],
    [/\btogether\b/gi, 'juntos'],
    [/\bforward\b/gi, 'para frente'],
    [/\bbackward\b/gi, 'para tras'],

    // ─── Adjetivos e estados ───
    [/\bpressed against\b/gi, 'pressionadas contra'],
    [/\bpressed\b/gi, 'pressionado'],
    [/\bbent\b/gi, 'flexionados'],
    [/\btight\b/gi, 'contraido'],
    [/\bflat on the ground\b/gi, 'apoiados no chao'],
    [/\bflat on the floor\b/gi, 'apoiados no chao'],
    [/\bflat on a bench\b/gi, 'apoiado em um banco'],
    [/\bpointed\b/gi, 'apontando'],
    [/\blocked\b/gi, 'travados'],
    [/\bfirmly\b/gi, 'firmemente'],
    [/\bsecurely\b/gi, 'com firmeza'],
    [/\bgently\b/gi, 'suavemente'],

    // ─── Possessivos e pronomes que sobraram ───
    [/\byour\b/gi, 'seus'],
    [/\byou\b/gi, 'voce'],
    [/behind/gi, 'atras'],
    [/should be/gi, 'deve estar'],
    [/make sure/gi, 'Certifique-se'],
    [/ensure that/gi, 'Garanta que'],

    // ─── Corrigir bug do bar/barbell ───
    [/the bar\b/gi, 'a barra'],
    [/the barbell\b/gi, 'a barra'],
    [/the dumbbell\b/gi, 'o haltere'],
    [/the dumbbells\b/gi, 'os halteres'],
    [/the weight\b/gi, 'o peso'],
    [/the weights\b/gi, 'os pesos'],
    [/the handle\b/gi, 'a alca'],
    [/the cable\b/gi, 'o cabo'],
    [/the band\b/gi, 'o elastico'],
    [/the machine\b/gi, 'a maquina'],
    [/the rope\b/gi, 'a corda'],
    [/a barbell\b/gi, 'uma barra'],
    // ─── Por fim, palavras isoladas que sobraram ───
    [/sit on\b/gi, 'Sente-se no'],
    [/\bhigh\b/gi, 'alto'],
    [/\blow\b/gi, 'baixo'],
    [/\bstart\b/gi, 'Comece'],
    [/\bhold\b(?!ing)/gi, 'segure'],
    [/\bheld\b/gi, 'segure'],
    [/\battach\b/gi, 'Prenda'],
    [/\battached\b/gi, 'Preso'],
    [/\bonto\b/gi, 'sobre'],
    [/\binto\b/gi, 'dentro de'],
    [/\bextended\b/gi, 'estendido'],
    [/\bfacing\b/gi, 'voltado'],
    [/\btreadmill\b/gi, 'esteira'],
    [/\bhanging\b/gi, 'pendurado'],
    [/\bfully\b/gi, 'completamente'],
    [/\bslightly\b/gi, 'ligeiramente'],
    [/\bplace\b/gi, 'posicione'],
    [/\bequipment\b/gi, 'equipamento'],
    [/\bdesired\b/gi, 'desejado'],
    [/\bintensity\b/gi, 'intensidade'],
    [/\bplatform\b/gi, 'plataforma'],
    [/\bfootrests?\b/gi, 'apoio para os pes'],
    [/\bcomfortable\b/gi, 'confortavel'],
    [/\bposition\b/gi, 'posicao'],
    [/\bexercise\b/gi, 'exercicio'],
    [/\bperform\b/gi, 'execute'],
    [/\bthroughout\b/gi, 'durante'],
    [/\bmaintain\b/gi, 'mantenha'],
    [/\brelease\b/gi, 'solte'],
    [/\ballow\b/gi, 'permita'],
    [/\bavoid\b/gi, 'evite'],
    [/\breturn\b/gi, 'retorne'],
    [/\bcontinue\b/gi, 'continue'],
    [/\blevel\b/gi, 'nivel'],
    [/\bhandle\b/gi, 'alca'],
    [/\bhandles\b/gi, 'alcas'],
    [/\bpulley\b/gi, 'polia'],
    [/\battachment\b/gi, 'acessorio'],
    [/\bextend\b/gi, 'estenda'],
    [/\bflex\b/gi, 'flexione'],
    [/\bcontract\b/gi, 'contraia'],
    [/\brepeat\b/gi, 'repita'],
    [/\balternate\b/gi, 'alterne'],
    [/\bswitch\b/gi, 'troque'],
    [/\bsqueeze\b/gi, 'contraia'],
    [/\bcomplete\b/gi, 'complete'],

    // ─── Equipamentos nos passos ───
    [/\ba dumbbell\b/gi, 'um haltere'],
    [/\bdumbbells\b/gi, 'halteres'],
    [/\bdumbbell\b/gi, 'haltere'],
    [/\ba barbell\b/gi, 'uma barra'],
    [/\bbarbells?\b/gi, 'barra'],
    [/\ba kettlebell\b/gi, 'um kettlebell'],
    [/\ba band\b/gi, 'um elastico'],
    [/\bresistance band\b/gi, 'elastico de resistencia'],
    [/\bbands\b/gi, 'elasticos'],
    [/\ba cable\b/gi, 'um cabo'],
    [/\bcables\b/gi, 'cabos'],
    [/\bbench\b/gi, 'banco'],
    [/\ban exercise ball\b/gi, 'uma bola de exercicio'],
    [/\ba stability ball\b/gi, 'uma bola de pilates'],
    [/\ba medicine ball\b/gi, 'uma bola de medicina'],

    // ─── Mais verbos e expressoes ───
    [/\bresting on\b/gi, 'apoiado sobre'],
    [/\bresting\b/gi, 'apoiado'],
    [/\blie on your back/gi, 'Deite-se de costas'],
    [/\blie on your side/gi, 'Deite-se de lado'],
    [/\blie on your stomach/gi, 'Deite-se de brucos'],
    [/\blie on a\b/gi, 'Deite-se em um'],
    [/\blie on the\b/gi, 'Deite-se no'],
    [/\beach\b/gi, 'cada'],
    [/\bwider than\b/gi, 'mais aberto que'],
    [/\bnarrower than\b/gi, 'mais fechado que'],
    [/\bsupported by\b/gi, 'apoiado por'],
    [/\bbe sure to\b/gi, 'Lembre-se de'],
    [/\bpalms ?facing ?(forward|front|away)/gi, 'palmas voltadas para frente'],
    [/\bpalms ?facing ?(down|downward)/gi, 'palmas voltadas para baixo'],
    [/\bpalms ?facing ?(up|upward)/gi, 'palmas voltadas para cima'],
    [/\bpalms ?facing ?(each other|inward)/gi, 'palmas voltadas uma para a outra'],

    // ─── Batch final: +50 palavras de alta frequencia ───
    [/\bthe\b(?!\s*(ground|floor|bench|bar|weight|handle|cable|band|machine|rope|dumbbell|barbell|starting|movement|exercise))/gi, 'o'],
    [/\bin\b(?!\s*(front|line|the|a|each|one|both|each))/gi, 'em'],
    [/\bset\b/gi, 'Ajuste'],
    [/\bby\s+(lying|holding|keeping|pushing|pulling)\b/gi, '$1'],
    [/\bflat\b(?!\s*(on|bench))/gi, 'plano'],
    [/\bpad\b/gi, 'apoio'],
    [/\bheight\b/gi, 'altura'],
    [/\bside\b(?!\s*(plank|bend|lying|lunge|raise|bridge|step))/gi, 'lado'],
    [/\bfacing up\b/gi, 'voltado para cima'],
    [/\bfacing down\b/gi, 'voltado para baixo'],
    [/\bup\b(?!\s*(straight|to|from|against|with))/gi, 'para cima'],
    [/\bdown\b(?!\s*(to|from|against|with|and))/gi, 'para baixo'],
    [/\bwidth\b/gi, 'largura'],
    [/\bangle\b/gi, 'angulo'],
    [/\bdegree\b/gi, 'graus'],
    [/\bcomfortable\b/gi, 'confortavel'],
    [/\bappropriate\b/gi, 'adequado'],
    [/\bintensity\b/gi, 'intensidade'],
    [/\bdesired\b/gi, 'desejado'],
    [/\bnatural\b/gi, 'natural'],
    [/\bproper\b/gi, 'adequada'],
    [/\bform\b/gi, 'postura'],
    [/\bpace\b/gi, 'ritmo'],
    [/\boption\b/gi, 'opcao'],
    [/\boptions\b/gi, 'opcoes'],
    [/\balternative\b/gi, 'alternativa'],
    [/\bwithout\b/gi, 'sem'],
    [/\bduring\b/gi, 'durante'],
    [/\buntil\b/gi, 'ate'],
    [/\bwhen\b/gi, 'quando'],
    [/\bwhile\b/gi, 'enquanto'],
    [/\bas\b/gi, 'enquanto'],
    [/\bmore\b/gi, 'mais'],
    [/\bless\b/gi, 'menos'],
    [/\bother\b/gi, 'outro'],
    [/\bsame\b/gi, 'mesmo'],
    [/\bone\b(?!\s*(arm|leg|hand|foot|end|side|time))/gi, 'um'],
    [/\btwo\b/gi, 'dois'],
    [/\bthree\b/gi, 'tres'],
    [/\bboth\b/gi, 'ambos'],
    [/\bnow\b/gi, 'agora'],
    [/\bagain\b/gi, 'novamente'],
    [/\bonly\b/gi, 'apenas'],
    [/\balways\b/gi, 'sempre'],
    [/\bnever\b/gi, 'nunca'],
    [/\bpossible\b/gi, 'possivel'],
    [/\blevel\b/gi, 'nivel'],
    [/\bhalf\b/gi, 'meio'],
    [/\bfuller\b/gi, 'mais completo'],
    [/\bpart\b/gi, 'parte'],
    [/\bwhole\b/gi, 'todo'],
    [/\bentire\b/gi, 'inteiro'],
  ]

  let result = step
  for (const [pattern, replacement] of map) {
    result = result.replace(pattern, replacement)
  }
  result = result.charAt(0).toUpperCase() + result.slice(1)
  return result
}

function translateName(name: string): string {
  const key = name.toLowerCase().trim()
  if (exerciseNameTranslations[key]) return exerciseNameTranslations[key]

  let t = name
    .replace(/\s*\(male\)/gi, '')
    .replace(/\s*\(female\)/gi, '')
    .replace(/\s*\(kneeling\)/gi, '')
    .replace(/\s*\(with\s+towel\)/gi, '')
    .trim()

  const wordMap: [RegExp, string][] = [
    // Equipment prefixes → suffixes in PT
    [/\b(barbell)\b/gi, 'com Barra'],
    [/\b(dumbbells?)\b/gi, 'com Halteres'],
    [/\b(kettlebells?)\b/gi, 'com Kettlebell'],
    [/\b(cables?)\b/gi, 'na Polia'],
    [/\b(machine)\b/gi, 'na Maquina'],
    [/\b(smith)\s+(machine)?/gi, 'Smith'],
    [/\b(lever)\s+(machine)?/gi, 'Maquina de Alavanca'],
    [/\b(bands?)\b(?!\s*(bell|bent|bicycle|concentration|front|hip|horizontal|jack|one|two|alternating|assisted|close|fixed|pull|push))/gi, 'com Elastico'],
    [/\b(body\s*weight)\b/gi, 'Peso Corporal'],
    [/\b(medicine\s*ball)\b/gi, 'Bola de Medicina'],
    [/\b(stability\s*ball|exercise\s*ball)\b/gi, 'Bola de Pilates'],
    [/\b(e-z\s*bar|ez\s*bar)\b/gi, 'Barra W'],
    [/\b(trap\s*bar)\b/gi, 'Barra Hexagonal'],
    [/\b(sled\s*machine)\b/gi, 'Treno de Arrasto'],
    [/\b(roller|wheel\s*roller)\b/gi, 'Roda Abdominal'],
    [/\b(bosu\s*ball)\b/gi, 'Bosu'],

    // Positions
    [/\b(lying)\b/gi, 'Deitado'],
    [/\b(seated)\b/gi, 'Sentado'],
    [/\b(standing)\b/gi, 'em Pe'],
    [/\b(incline)\b/gi, 'Inclinado'],
    [/\b(decline)\b/gi, 'Declinado'],
    [/\b(prone)\b/gi, 'Pronado'],
    [/\b(supine)\b/gi, 'Supino'],
    [/\b(kneeling)\b/gi, 'Ajoelhado'],
    [/\b(overhead)\b/gi, 'Acima da Cabeca'],
    [/\b(bent[\s-]?over)\b/gi, 'Curvado'],
    [/\b(all\s*fours)\b/gi, 'Quadrupede'],
    [/\b(side\s*lying)\b/gi, 'Deitado de Lado'],

    // Grips and variants  
    [/\b(wide[\s-]?grip)\b/gi, 'Pegada Aberta'],
    [/\b(close[\s-]?grip)\b/gi, 'Pegada Fechada'],
    [/\b(underhand)\b/gi, 'Supinada'],
    [/\b(overhand)\b/gi, 'Pronada'],
    [/\b(reverse\s*grip)\b/gi, 'Pegada Inversa'],
    [/\b(neutral\s*grip)\b/gi, 'Pegada Neutra'],
    [/\b(palms?\s*facing)\b/gi, 'Palmas Voltadas'],
    [/\b(parallel)\b/gi, 'Paralela'],

    // Qualifiers
    [/\b(reverse)\b/gi, 'Inverso'],
    [/\b(alternating|alternate)\b/gi, 'Alternado'],
    [/\b(assisted)\b/gi, 'Assistido'],
    [/\b(weighted)\b/gi, 'com Peso'],
    [/\b(single[\s-]?(arm|leg|side)?)\b/gi, 'Unilateral'],
    [/\b(one[\s-]?arm)\b/gi, 'Unilateral'],
    [/\b(two[\s-]?arm)\b/gi, 'Bilateral'],
    [/\b(double)\b/gi, 'Duplo'],
    [/\b(both)\b/gi, 'Ambos'],
    [/\b(side)\b(?!\s*(lying|plank|bend|raise|lateral|lunge|bridge|step|hopping|jump|to|kick|split|stretch|leg|glide|crunch|shuffle|wrist|neck|back))/gi, 'Lateral'],
    [/\b(front)\b(?!\s*(raise|squat|lever|pull|box|cone|leg|plate|lateral))/gi, 'Frontal'],
    [/\b(rear)\b/gi, 'Posterior'],
    [/\b(backward)\b/gi, 'para Tras'],
    [/\b(forward)\b/gi, 'para Frente'],
    [/\b(lateral)\b(?!\s*(raise|pulldown|box|step|lunge|hop|jump|shuffle|walk|slide|lunge|plank|bound))/gi, 'Lateral'],
    [/\b(straight[\s-]?(arm|leg|bar)?)\b/gi, 'Estendido'],
    [/\b(fixed)\b/gi, 'Fixo'],
    [/\b(scapular)\b/gi, 'Escapular'],

    // Body parts
    [/\b(ankles?)\b/gi, 'Tornozelo'],
    [/\b(calves?|calf)\b/gi, 'Panturrilha'],
    [/\b(hamstrings?|hamstring)\b/gi, 'Posterior de Coxa'],
    [/\b(quadriceps|quads?)\b/gi, 'Quadriceps'],
    [/\b(glutes?|gluteus|glute)\b/gi, 'Gluteo'],
    [/\b(hip\s*flexors?)\b/gi, 'Flexor do Quadril'],
    [/\b(hips?)\b(?!\s*(flexor|thrust|lift|raise|abduction|adduction|extension|circle|rotation|hinge|roll|drive|lock|bridge))/gi, 'Quadril'],
    [/\b(adductors?)\b/gi, 'Adutor'],
    [/\b(abductors?)\b/gi, 'Abdutor'],
    [/\b(piriformis)\b/gi, 'Piriforme'],
    [/\b(obliques?)\b/gi, 'Obliquo'],
    [/\b(abdominals?|abs?)\b(?!\s*(roller|wheel|bench|coaster|crunch|circle))/gi, 'Abdomen'],
    [/\b(core)\b/gi, 'Core'],
    [/\b(rectus\s*femoris)\b/gi, 'Reto Femoral'],
    [/\b(pectoralis?\s*major)\b/gi, 'Peitoral Maior'],
    [/\b(pec)\b/gi, 'Peitoral'],
    [/\b(serratus)\b/gi, 'Serrátil'],
    [/\b(scapulae?)\b/gi, 'Escapula'],
    [/\b(rotator\s*cuff)\b/gi, 'Manguito Rotador'],
    [/\b(shoulders?|delts?|deltoids?)\b/gi, 'Ombro'],
    [/\b(chest)\b/gi, 'Peito'],
    [/\b(trapezius|traps?)\b/gi, 'Trapezio'],
    [/\b(lats?|latissimus)\b/gi, 'Dorsal'],
    [/\b(rhomboids?)\b/gi, 'Romboides'],
    [/\b(triceps?|tricep)\b/gi, 'Triceps'],
    [/\b(biceps?|bicep)\b/gi, 'Biceps'],
    [/\b(brachialis)\b/gi, 'Braquial'],
    [/\b(brachioradialis)\b/gi, 'Braquiorradial'],
    [/\b(forearms?|forearm)\b/gi, 'Antebraco'],
    [/\b(wrists?|wrist)\b/gi, 'Punho'],
    [/\b(fingers?|finger)\b/gi, 'Dedo'],
    [/\b(thumbs?|thumb)\b/gi, 'Polegar'],
    [/\b(grip|gripping)\b/gi, 'Pegada'],
    [/\b(hand)\b/gi, 'Mao'],
    [/\b(neck)\b/gi, 'Pescoco'],
    [/\b(spine|spinal)\b/gi, 'Coluna'],
    [/\b(lower\s*back)\b/gi, 'Lombar'],
    [/\b(thighs?)\b/gi, 'Coxa'],
    [/\b(knees?)\b/gi, 'Joelho'],
    [/\b(kicks?)\b/gi, 'Chute'],
    [/\b(shins?)\b/gi, 'Tibia'],
    [/\b(soleus)\b/gi, 'Soleo'],
    [/\b(gastrocnemius)\b/gi, 'Gastrocnêmio'],
    [/\b(tibialis)\b/gi, 'Tibial'],
    [/\b(tendon)\b/gi, 'Tendao'],
    [/\b(achilles)\b/gi, 'Aquiles'],
    [/\b(elbows?)\b/gi, 'Cotovelo'],
    [/\b(limb)\b/gi, 'Membro'],

    // Exercise types
    [/\b(curls?)\b(?!.*(bar|wrist|hammer|reverse|preacher|concentration|zottman|drag|spider|incline|decline|pinwheel))/gi, 'Rosca'],
    [/\b(raises?|raise)\b(?!.*(front|lateral|side|calf|leg|knee|heel|shoulder|straight|lying|seated|standing))/gi, 'Elevacao'],
    [/\b(rows?|row)\b(?!.*(upright|bent|t-bar|cable|dumbbell|barbell|lever|seated|incline|one-arm|single-arm|reverse|band))/gi, 'Remada'],
    [/\b(press)\b(?!.*(bench|shoulder|overhead|military|leg|french|floor|close-grip|wide-grip|decline|incline|arnold|push|pallof|svend))/gi, 'Desenvolvimento'],
    [/\b(squats?|squat)\b(?!.*(hack|split|goblet|pistol|bulgarian|cossack|sissy|sumo|zercher|front|overhead|box|jump|band|smith|lever|barbell|dumbbell|kettlebell|bodyweight))/gi, 'Agachamento'],
    [/\b(extensions?|extension)\b(?!.*(leg|tricep|hip|back|wrist|knee|overhead|lying|seated|standing|cable))/gi, 'Extensao'],
    [/\b(flys?|flyes?|flies)\b/gi, 'Crucifixo'],
    [/\b(shrugs?)\b/gi, 'Encolhimento'],
    [/\b(lunges?|lunge)\b(?!.*(walking|reverse|side|jumping|curtsy|static|barbell|dumbbell|kettlebell|cable|smith))/gi, 'Avanco'],
    [/\b(crunches?|crunch)\b(?!.*(bicycle|reverse|oblique|cable|decline|weighted|standing|side|jack|knife|cross|body|cocoon|butterfly|double|flutter|gorilla|pulse))/gi, 'Abdominal'],
    [/\b(push[\s-]?ups?|push\s*ups?|pushup)\b/gi, 'Flexao de Braco'],
    [/\b(pull[\s-]?ups?|pullups?|chin[\s-]?ups?|chinups?)\b/gi, 'Barra Fixa'],
    [/\b(pull[\s-]?downs?|pulldowns?|pulldown)\b/gi, 'Puxada no Pulley'],
    [/\b(pull[\s-]?overs?|pullovers?)\b/gi, 'Pullover'],
    [/\b(deadlifts?|deadlift)\b/gi, 'Levantamento Terra'],
    [/\b(dips?)\b(?!.*(bench|tricep|chest|assisted|weighted|machine|ring|bar|parallel))/gi, 'Paralelas'],
    [/\b(planks?)\b/gi, 'Prancha'],
    [/\b(bridges?)\b/gi, 'Ponte'],
    [/\b(thrusts?|thrust)\b/gi, 'Elevacao de Quadril'],
    [/\b(swings?|swing)\b/gi, 'Balanceio'],
    [/\b(stretch(?:es|ing)?)\b/gi, 'Alongamento'],
    [/\b(jumps?|jumping)\b/gi, 'Salto'],
    [/\b(hops?|hopping)\b/gi, 'Pulo'],
    [/\b(walks?|walking)\b/gi, 'Caminhada'],
    [/\b(runs?|running|sprints?|sprint)\b/gi, 'Corrida'],
    [/\b(steps?|step)\b(?!.*(up|mill|down|platform))/gi, 'Passo'],
    [/\b(cleans?|clean)\b/gi, 'Clean'],
    [/\b(snatch(?:es)?)\b/gi, 'Snatch'],
    [/\b(jerks?|jerk)\b/gi, 'Jerk'],
    [/\b(throw)\b/gi, 'Lancamento'],
    [/\b(catch)\b/gi, 'Recepcao'],
    [/\b(circles?)\b/gi, 'Circulo'],
    [/\b(rotations?|rotation)\b/gi, 'Rotacao'],
    [/\b(twists?|twist)\b/gi, 'Torcao'],
    [/\b(touchers?|touch)\b/gi, 'Toque'],
    [/\b(claps?|clapping|clap)\b/gi, 'Palma'],
    [/\b(holds?|holding)\b/gi, 'Estatico'],
    [/\b(reaches?|reach)\b/gi, 'Alcance'],
    [/\b(pulls?)\b(?!.*(up|down|over|through|back|apart))/gi, 'Puxada'],
    [/\b(pushes?)\b(?!.*(up|down|through|back|away|press))/gi, 'Empurrao'],
    [/\b(bends?|bend)\b(?!.*(over|side))/gi, 'Flexao'],
    [/\b(sits?[\s-]?ups?|situp)\b/gi, 'Abdominal'],
    [/\b(roll[\s-]?outs?|rollout)\b/gi, 'Rolamento'],
    [/\b(motion)\b/gi, 'Movimento'],
    [/\b(dynamic)\b/gi, 'Dinamico'],
    [/\b(static)\b/gi, 'Estatico'],
    [/\b(isometric)\b/gi, 'Isometrico'],
    [/\b(concentration)\b/gi, 'Concentrado'],
    [/\b(drag)\b/gi, 'Arrasto'],
    [/\b(sled)\b/gi, 'Treno'],

    // Common movements
    [/\b(hanging)\b/gi, 'Suspenso'],
    [/\b(throw\s*down)\b/gi, 'Lancamento para Baixo'],
    [/\b(pull\s*apart)\b/gi, 'Abertura'],
    [/\b(hip\s*lift)\b/gi, 'Elevacao de Quadril'],
    [/\b(hip\s*hinge)\b/gi, 'Dobradica de Quadril'],
    [/\b(hip\s*circle)\b/gi, 'Circulo de Quadril'],
    [/\b(leg\s*raise)\b/gi, 'Elevacao de Pernas'],
    [/\b(knee\s*raise)\b/gi, 'Elevacao de Joelhos'],
    [/\b(heel\s*touch)\b/gi, 'Toque de Calcanhar'],
    [/\b(calf\s*raise)\b/gi, 'Elevacao de Panturrilha'],
    [/\b(glute\s*kickback)\b/gi, 'Coice de Gluteo'],
    [/\b(chest\s*press)\b/gi, 'Supino'],
    [/\b(chest\s*fly)\b/gi, 'Crucifixo'],
    [/\b(shoulder\s*press)\b/gi, 'Desenvolvimento'],
    [/\b(front\s*raise)\b/gi, 'Elevacao Frontal'],
    [/\b(lateral\s*raise)\b/gi, 'Elevacao Lateral'],
    [/\b(side\s*bend)\b/gi, 'Inclinacao Lateral'],
    [/\b(side\s*plank)\b/gi, 'Prancha Lateral'],
    [/\b(face\s*pull)\b/gi, 'Face Pull'],
    [/\b(skull\s*crusher)\b/gi, 'Triceps Testa'],
    [/\b(kick\s*back)\b/gi, 'Coice'],
    [/\b(pull\s*through)\b/gi, 'Puxada entre Pernas'],
    [/\b(around\s*the\s*world)\b/gi, 'Volta ao Mundo'],
    [/\b(wood\s*chop)\b/gi, 'Lenha'],
    [/\b(pallof\s*press)\b/gi, 'Pallof Press'],
    [/\b(arnold\s*press)\b/gi, 'Desenvolvimento Arnold'],
    [/\b(svend\s*press)\b/gi, 'Svend Press'],
    [/\b(tate\s*press)\b/gi, 'Tate Press'],
    [/\b(cuban\s*press)\b/gi, 'Cuban Press'],
    [/\b(bradford\s*press)\b/gi, 'Bradford Press'],
    [/\b(scott\s*press)\b/gi, 'Scott Press'],

    // Cleanup conjunctions  
    [/\b(with)\b/gi, 'com'],
    [/\b(and)\b/gi, 'e'],
    [/\b(on)\b/gi, 'no'],
    [/\b(of)\b/gi, 'de'],
    [/\b(from)\b/gi, 'do'],
    [/\b(to)\b/gi, 'para'],
    [/\b(off)\b/gi, 'fora'],
    [/\b(behind)\b/gi, 'atras'],
    [/\b(between)\b/gi, 'entre'],
    [/\b(above)\b/gi, 'acima'],
    [/\b(below)\b/gi, 'abaixo'],
    [/\b(across)\b/gi, 'atraves'],
  ]

  const lower = t.toLowerCase().trim()
  for (const [pattern, replacement] of wordMap) {
    t = t.replace(pattern, replacement)
  }

  t = t.replace(/\s+/g, ' ').trim()
  t = t.charAt(0).toUpperCase() + t.slice(1)

  if (t === name || t.toLowerCase() === name.toLowerCase()) {
    for (const [pattern, replacement] of wordMap) {
      const r2 = t.replace(pattern, replacement)
      if (r2 !== t) { t = r2; break }
    }
  }

  return t || name
}

async function sync() {
  console.log('Limpando exercicios antigos...')
  const deleted = await prisma.exercicio.deleteMany({
    where: { id: { not: { startsWith: 'ds-' } } }
  })
  console.log(`${deleted.count} exercicios antigos removidos.`)

  const dataPath = findDatasetPath()
  console.log(`Carregando dataset: ${dataPath}`)
  const exercises: any[] = JSON.parse(fs.readFileSync(dataPath, 'utf-8'))
  console.log(`${exercises.length} exercicios encontrados.`)

  let count = 0, errors = 0
  const BATCH = 50

  for (let i = 0; i < exercises.length; i += BATCH) {
    const batch = exercises.slice(i, i + BATCH)
    await Promise.all(batch.map(async (ex) => {
      try {
        const nomePT = translateName(ex.name)
        const imagemUrl = ex.image ? `${API_BASE_URL}/exercises/${ex.image}` : null
        const gifUrl = ex.gif_url ? `${API_BASE_URL}/exercises/${ex.gif_url}` : null
        const grupoMuscular = muscleGroupPT[ex.body_part?.toLowerCase()] || muscleGroupPT[ex.muscle_group?.toLowerCase()] || ex.body_part || ex.muscle_group || ''
        const equipamento = equipmentPT[ex.equipment?.toLowerCase()] || ex.equipment || 'Peso Corporal'
        const musculoAlvo = muscleGroupPT[ex.target?.toLowerCase()] || muscleGroupPT[ex.muscle_group?.toLowerCase()] || ex.target || ex.muscle_group || ''
        const musculosSecundarios = (ex.secondary_muscles || []).map((m: string) => muscleGroupPT[m.toLowerCase()] || m)
        const passosEN: string[] = ex.instruction_steps?.en || []
        const passosPT = passosEN.map(translateStep)
        const descricaoEN: string = ex.instructions?.en || ''
        const descricaoPT = descricaoEN ? translateStep(descricaoEN) : passosPT.join(' ')
        const dica = `${bodyPartPT[ex.body_part?.toLowerCase()] || ex.body_part || ''} | ${grupoMuscular}`
        const exercicioId = `ds-${ex.id}`

        await prisma.exercicio.upsert({
          where: { id: exercicioId },
          create: { id: exercicioId, nome: nomePT, grupo_muscular: grupoMuscular, equipamento, imagem_url: imagemUrl, gif_url: gifUrl, descricao_pt: descricaoPT, passos_pt: passosPT, musculo_alvo: musculoAlvo, musculos_secundarios: musculosSecundarios, dica, nivel: 'Intermediario' },
          update: { nome: nomePT, grupo_muscular: grupoMuscular, equipamento, imagem_url: imagemUrl, gif_url: gifUrl, descricao_pt: descricaoPT, passos_pt: passosPT, musculo_alvo: musculoAlvo, musculos_secundarios: musculosSecundarios, dica },
        })
        count++
      } catch (err) {
        errors++
        console.error(`Erro em ${ex.id} (${ex.name}):`, err)
      }
    }))
    console.log(`${Math.min(i + BATCH, exercises.length)}/${exercises.length} processados...`)
  }

  console.log(`Sincronizacao concluida! ${count} exercicios importados. ${errors} erros.`)
}

sync().catch(console.error).finally(() => prisma.$disconnect())
