/**
 * translate-utils.ts
 * Funcao compartilhada de traducao EN->PT para exercicios.
 */

export function translateToPt(text: string): string {
  if (!text || typeof text !== 'string') return text

  let s = text.trim()

  const phraseRules: [RegExp, string][] = [
    // ── Frases completas comuns ──
    [/Lower your body into a squat position/gi, 'Abaixe o corpo na posicao de agachamento'],
    [/Lower your body/gi, 'Abaixe o corpo'],
    [/slowly lower the weight/gi, 'abaixe a carga lentamente'],
    [/slowly return to( the)? starting position/gi, 'retorne lentamente a posicao inicial'],
    [/return to( the)? starting position/gi, 'retorne a posicao inicial'],
    [/starting position/gi, 'posicao inicial'],
    [/keep your back straight/gi, 'mantenha as costas retas'],
    [/keep your core tight/gi, 'mantenha o abdomen contraido'],
    [/keep your core engaged/gi, 'mantenha o abdomen contraido'],
    [/feet shoulder-width apart/gi, 'pes na largura dos ombros'],
    [/shoulder-width apart/gi, 'na largura dos ombros'],
    [/through the full range of motion/gi, 'em toda a amplitude do movimento'],
    [/full range of motion/gi, 'amplitude completa do movimento'],
    [/range of motion/gi, 'amplitude de movimento'],
    [/with control/gi, 'com controle'],
    [/in a controlled manner/gi, 'de forma controlada'],
    [/squeeze your/gi, 'contraia seus'],
    [/at the top of the movement/gi, 'no topo do movimento'],
    [/at the bottom of the movement/gi, 'na parte mais baixa do movimento'],
    [/top of the movement/gi, 'topo do movimento'],
    [/bottom of the movement/gi, 'parte mais baixa do movimento'],
    [/make sure to/gi, 'certifique-se de'],
    [/keep your elbows/gi, 'mantenha os cotovelos'],
    [/keep your elbows slightly bent/gi, 'mantenha os cotovelos levemente flexionados'],
    [/slightly bent/gi, 'levemente flexionados'],
    [/fully extended/gi, 'totalmente estendidos'],
    [/palms facing/gi, 'palmas voltadas'],
    [/throughout the movement/gi, 'durante todo o movimento'],
    [/throughout the exercise/gi, 'durante todo o exercicio'],
    [/drive through your heels/gi, 'empurre pelos calcanhares'],
    [/drive through your/gi, 'empurre com'],
    [/breathe out/gi, 'expire'],
    [/breathe in/gi, 'inspire'],
    [/exhale as you/gi, 'expire ao'],
    [/inhale as you/gi, 'inspire ao'],
    [/pause for a moment/gi, 'faça uma breve pausa'],
    [/hold for a second/gi, 'segure por um segundo'],
    [/hold for/gi, 'segure por'],
    [/push through/gi, 'empurre com'],
    [/pull toward/gi, 'puxe em direção a'],
    [/repeat for( the)? desired number of/gi, 'repita pelo numero prescrito de'],
    [/repeat for prescribed/gi, 'repita pelas'],
    [/do not lock your/gi, 'nao trave seus'],
    [/avoid locking/gi, 'evite travar'],
    [/do not use momentum/gi, 'nao use impulso'],
    [/without using momentum/gi, 'sem usar impulso'],
    [/focus on/gi, 'concentre-se em'],
    [/keep your chest up/gi, 'mantenha o peito erguido'],
    [/keep your head neutral/gi, 'mantenha a cabeca em posicao neutra'],
    [/keep your wrists/gi, 'mantenha os pulsos'],
    [/keep your shoulders/gi, 'mantenha os ombros'],
    [/keep your gaze/gi, 'mantenha o olhar'],
    [/look straight ahead/gi, 'olhe para frente'],
    [/engage your/gi, 'ative seu'],
    [/do not arch your back/gi, 'nao arqueie as costas'],
    [/do not round your back/gi, 'nao arredonde as costas'],
    [/maintain a neutral spine/gi, 'mantenha a coluna neutra'],
    [/neutral spine/gi, 'coluna neutra'],
  ]

  for (const [pattern, replacement] of phraseRules) {
    s = s.replace(pattern, replacement)
  }

  const wordRules: [RegExp, string][] = [
    // ── Equipamentos ──
    [/\bbarbell\b/gi, 'barra'],
    [/\bdumbbell\b/gi, 'halter'],
    [/\bdumbbells\b/gi, 'halteres'],
    [/\bkettlebell\b/gi, 'kettlebell'],
    [/\bresistance band\b/gi, 'faixa elastica'],
    [/\bresistance bands\b/gi, 'faixas elasticas'],
    [/\bcable\b/gi, 'cabo'],
    [/\bcables\b/gi, 'cabos'],
    [/\bpulley\b/gi, 'polia'],
    [/\bmachine\b/gi, 'maquina'],
    [/\bbench\b/gi, 'banco'],
    [/\bswiss ball\b/gi, 'bola suica'],
    [/\bstability ball\b/gi, 'bola de estabilidade'],
    [/\bfoam roller\b/gi, 'rolo de espuma'],
    [/\btrx\b/gi, 'TRX'],

    // ── Partes do corpo ──
    [/\bchest\b/gi, 'peito'],
    [/\bback\b/gi, 'costas'],
    [/\bshoulder\b/gi, 'ombro'],
    [/\bshoulders\b/gi, 'ombros'],
    [/\btriceps?\b/gi, 'triceps'],
    [/\bbiceps?\b/gi, 'biceps'],
    [/\bforearms?\b/gi, 'antebraço'],
    [/\bquadriceps?\b/gi, 'quadriceps'],
    [/\bquads?\b/gi, 'quadriceps'],
    [/\bhamstrings?\b/gi, 'isquiotibiais'],
    [/\bglutes?\b/gi, 'gluteos'],
    [/\bcalves?\b/gi, 'panturrilhas'],
    [/\babdomen\b/gi, 'abdomen'],
    [/\babs?\b/gi, 'abdomen'],
    [/\bcore\b/gi, 'core'],
    [/\blower back\b/gi, 'lombar'],
    [/\bupper back\b/gi, 'dorsal superior'],
    [/\btraps?\b/gi, 'trapezio'],
    [/\blats?\b/gi, 'dorsais'],
    [/\bdelts?\b/gi, 'deltoides'],
    [/\bobliques?\b/gi, 'obliquos'],
    [/\bhip flexors?\b/gi, 'flexores do quadril'],
    [/\bhips?\b/gi, 'quadril'],
    [/\bpelvis\b/gi, 'pelve'],
    [/\bwrist\b/gi, 'punho'],
    [/\bwrists\b/gi, 'pulsos'],
    [/\belbow\b/gi, 'cotovelo'],
    [/\belbows\b/gi, 'cotovelos'],
    [/\bknee\b/gi, 'joelho'],
    [/\bknees\b/gi, 'joelhos'],
    [/\bankle\b/gi, 'tornozelo'],
    [/\bankles\b/gi, 'tornozelos'],
    [/\bheel\b/gi, 'calcanhar'],
    [/\bheels\b/gi, 'calcanhares'],
    [/\btoes\b/gi, 'pontas dos pes'],
    [/\bfeet\b/gi, 'pes'],
    [/\bfoot\b/gi, 'pe'],
    [/\bshins?\b/gi, 'canela'],
    [/\bneck\b/gi, 'pescoço'],
    [/\bhead\b/gi, 'cabeca'],

    // ── Movimentos / exercicios ──
    [/\bsquat\b/gi, 'agachamento'],
    [/\bdeadlift\b/gi, 'levantamento terra'],
    [/\bbench press\b/gi, 'supino'],
    [/\bpress\b/gi, 'desenvolvimento'],
    [/\boverhead press\b/gi, 'desenvolvimento acima da cabeca'],
    [/\bshoulder press\b/gi, 'desenvolvimento de ombros'],
    [/\bpull.?up\b/gi, 'barra fixa'],
    [/\bchin.?up\b/gi, 'barra fixa supinada'],
    [/\bpush.?up\b/gi, 'flexao de braço'],
    [/\bcrunch\b/gi, 'abdominal'],
    [/\bsit.?up\b/gi, 'abdominal completo'],
    [/\brow\b/gi, 'remada'],
    [/\bcurl\b/gi, 'rosca'],
    [/\beginning.*curl\b/gi, 'rosca'],
    [/\bfly\b/gi, 'crucifixo'],
    [/\bflyes?\b/gi, 'crucifixos'],
    [/\bextension\b/gi, 'extensao'],
    [/\braise\b/gi, 'elevacao'],
    [/\bkickback\b/gi, 'coice'],
    [/\bpulldown\b/gi, 'puxada'],
    [/\bpushdown\b/gi, 'empurrada'],
    [/\bshrug\b/gi, 'encolhimento'],
    [/\blunge\b/gi, 'afundo'],
    [/\blunges?\b/gi, 'afundos'],
    [/\bplank\b/gi, 'prancha'],
    [/\bdip\b/gi, 'paralelas'],
    [/\bcrossover\b/gi, 'crossover'],
    [/\bleg press\b/gi, 'leg press'],
    [/\bleg curl\b/gi, 'flexora'],
    [/\bleg extension\b/gi, 'extensora'],
    [/\bswing\b/gi, 'balanço'],
    [/\bthruster\b/gi, 'thruster'],
    [/\bburpee\b/gi, 'burpee'],
    [/\bjump\b/gi, 'salto'],
    [/\bcalf raise\b/gi, 'elevacao de panturrilha'],
    [/\bhip thrust\b/gi, 'elevacao de quadril'],
    [/\bglute bridge\b/gi, 'ponte de gluteos'],
    [/\bface pull\b/gi, 'puxada facial'],
    [/\blateral raise\b/gi, 'elevacao lateral'],
    [/\bfront raise\b/gi, 'elevacao frontal'],
    [/\brear delt/gi, 'deltoide posterior'],
    [/\bgood morning\b/gi, 'bom dia'],
    [/\bclean\b/gi, 'arremesso'],
    [/\bsnatch\b/gi, 'arranco'],
    [/\bjerk\b/gi, 'arremesso'],
    [/\bcarry\b/gi, 'carregada'],

    // ── Verbos / acoes ──
    [/\blower\b/gi, 'abaixe'],
    [/\braise\b/gi, 'eleve'],
    [/\blift\b/gi, 'levante'],
    [/\bpush\b/gi, 'empurre'],
    [/\bpull\b/gi, 'puxe'],
    [/\bsqueeze\b/gi, 'contraia'],
    [/\bexhale\b/gi, 'expire'],
    [/\binhale\b/gi, 'inspire'],
    [/\bhold\b/gi, 'segure'],
    [/\brelease\b/gi, 'solte'],
    [/\bcontract\b/gi, 'contraia'],
    [/\bextend\b/gi, 'estenda'],
    [/\bflex\b/gi, 'flexione'],
    [/\brotate\b/gi, 'gire'],
    [/\bengage\b/gi, 'ative'],
    [/\btighten\b/gi, 'contraia'],
    [/\bkeep\b/gi, 'mantenha'],
    [/\bmaintain\b/gi, 'mantenha'],
    [/\bby driving\b/gi, 'empurrando'],
    [/\bby pushing\b/gi, 'empurrando'],
    [/\bby pulling\b/gi, 'puxando'],
    [/\bby squeezing\b/gi, 'contraindo'],

    // ── Adjetivos / descricoes ──
    [/\bslowly\b/gi, 'lentamente'],
    [/\bslow\b/gi, 'devagar'],
    [/\bfast\b/gi, 'rapido'],
    [/\bcontrolled\b/gi, 'controlado'],
    [/\bexplosive\b/gi, 'explosivo'],
    [/\bstanding\b/gi, 'em pe'],
    [/\bseated\b/gi, 'sentado'],
    [/\blying\b/gi, 'deitado'],
    [/\bprone\b/gi, 'de bruços'],
    [/\bsupine\b/gi, 'de costas'],
    [/\bincline\b/gi, 'inclinado'],
    [/\bdecline\b/gi, 'declinado'],
    [/\bflat\b/gi, 'reto'],
    [/\bunilateral\b/gi, 'unilateral'],
    [/\bbilateral\b/gi, 'bilateral'],
    [/\balternating\b/gi, 'alternado'],
    [/\bsupinated\b/gi, 'supinado'],
    [/\bpronated\b/gi, 'pronado'],
    [/\bneutral grip\b/gi, 'pegada neutra'],
    [/\bwide grip\b/gi, 'pegada aberta'],
    [/\bclose grip\b/gi, 'pegada fechada'],
    [/\boverhand grip\b/gi, 'pegada pronada'],
    [/\bunderhand grip\b/gi, 'pegada supinada'],
    [/\bhammer grip\b/gi, 'pegada martelo'],
    [/\bgrip\b/gi, 'pegada'],
    [/\bconcentric\b/gi, 'concentrica'],
    [/\beccentric\b/gi, 'excentrica'],
    [/\bisometric\b/gi, 'isometrica'],
    [/\bnegative\b/gi, 'negativa'],
    [/\bpositive\b/gi, 'positiva'],

    // ── Outros termos ──
    [/\brepetition\b/gi, 'repeticao'],
    [/\brepetitions\b/gi, 'repetições'],
    [/\breps?\b/gi, 'repeticoes'],
    [/\bsets?\b/gi, 'series'],
    [/\bweight\b/gi, 'carga'],
    [/\bweights?\b/gi, 'cargas'],
    [/\bheavy\b/gi, 'pesado'],
    [/\blight\b/gi, 'leve'],
    [/\bmoderate\b/gi, 'moderado'],
    [/\bmovement\b/gi, 'movimento'],
    [/\bposition\b/gi, 'posicao'],
    [/\bposture\b/gi, 'postura'],
    [/\bform\b/gi, 'execucao'],
    [/\btechnique\b/gi, 'tecnica'],
    [/\bpace\b/gi, 'ritmo'],
    [/\btempo\b/gi, 'cadencia'],
    [/\bbreathing\b/gi, 'respiracao'],
    [/\bbreath\b/gi, 'respiro'],
    [/\binhale\b/gi, 'inspire'],
    [/\bexhale\b/gi, 'expire'],
    [/\balignment\b/gi, 'alinhamento'],
    [/\bstability\b/gi, 'estabilidade'],
    [/\bbalance\b/gi, 'equilibrio'],
    [/\bflexibility\b/gi, 'flexibilidade'],
    [/\bmobility\b/gi, 'mobilidade'],
    [/\bstrength\b/gi, 'força'],
    [/\bendurance\b/gi, 'resistencia'],
    [/\bpower\b/gi, 'potencia'],
    [/\bwarm.?up\b/gi, 'aquecimento'],
    [/\bcool.?down\b/gi, 'desaquecimento'],
    [/\bstretch\b/gi, 'alongamento'],
    [/\bwarmup\b/gi, 'aquecimento'],
    [/\bcooldown\b/gi, 'desaquecimento'],
    [/\bupward\b/gi, 'para cima'],
    [/\bdownward\b/gi, 'para baixo'],
    [/\bforward\b/gi, 'para frente'],
    [/\bbackward\b/gi, 'para tras'],
    [/\bsideways\b/gi, 'lateralmente'],
    [/\bdiagonally\b/gi, 'diagonalmente'],
    [/\bhorizontally\b/gi, 'horizontalmente'],
    [/\bvertically\b/gi, 'verticalmente'],
    [/\bparallel\b/gi, 'paralelo'],
    [/\bperpendicular\b/gi, 'perpendicular'],
    [/\bgradually\b/gi, 'gradualmente'],
    [/\bprogressively\b/gi, 'progressivamente'],
    [/\bimmediately\b/gi, 'imediatamente'],
    [/\bsmoothly\b/gi, 'suavemente'],
    [/\bcontinuously\b/gi, 'continuamente'],
    [/\bsimultaneously\b/gi, 'simultaneamente'],
    [/\balternately\b/gi, 'alternadamente'],
    [/\bindependently\b/gi, 'independentemente'],
  ]

  for (const [pattern, replacement] of wordRules) {
    s = s.replace(pattern, replacement)
  }

  // ── Correções pos-replace ──
  s = s.replace(/\bsua pe\b/gi, 'seu pe')
  s = s.replace(/\bsuas pes\b/gi, 'seus pes')
  s = s.replace(/\bseus pes\b/gi, 'seus pes')
  s = s.replace(/\bseu abdomen\b/gi, 'seu abdomen')
  s = s.replace(/\bsuas costas\b/gi, 'suas costas')
  s = s.replace(/\bseus ombros\b/gi, 'seus ombros')
  s = s.replace(/\bseus joelhos\b/gi, 'seus joelhos')
  s = s.replace(/\bseus cotovelos\b/gi, 'seus cotovelos')
  s = s.replace(/\bseus bracos\b/gi, 'seus braços')
  s = s.replace(/\bsuas pernas\b/gi, 'suas pernas')
  s = s.replace(/\bseus dedos\b/gi, 'seus dedos')
  s = s.replace(/\bsuas maos\b/gi, 'suas maos')

  // ── Limpeza final ──
  s = s.replace(/\s+/g, ' ').trim()
  if (s.length > 0) {
    s = s.charAt(0).toUpperCase() + s.slice(1)
    if (!/[.!?]$/.test(s)) s += '.'
  }

  return s
}
